version: "3.8"

services:
  bigdata:
    build: .
    container_name: bigdata-container
    hostname: namenode
    ports:
      - "22:22"
      - "8888:8888"
      - "9870:9870"
      - "8088:8088"
      - "8042:8042"
      - "19888:19888"
      - "9092:9092"
      - "2181:2181"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - SPARK_HOME=/opt/spark
      - KAFKA_HOME=/opt/kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://namenode:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
    volumes:
      - hadoop_data:/opt/hadoop_data
      - ./notebooks:/notebooks
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  hadoop_data: